export const QRL_ADDRESS_PREFIX = "Q";
export const QRL_ADDRESS_BYTES = 64;
export const QRL_ADDRESS_HEX_LENGTH = QRL_ADDRESS_BYTES * 2;
export const QRL_ADDRESS_LENGTH = QRL_ADDRESS_PREFIX.length + QRL_ADDRESS_HEX_LENGTH;

export const QRL_ZERO_ADDRESS =
  `${QRL_ADDRESS_PREFIX}${"0".repeat(QRL_ADDRESS_HEX_LENGTH)}` as const;

export const QRL_EXAMPLE_ADDRESS =
  `${QRL_ADDRESS_PREFIX}${"8a".repeat(QRL_ADDRESS_BYTES)}`;

export const QRL_EXAMPLE_ADDRESS_2 =
  `${QRL_ADDRESS_PREFIX}${"07".repeat(QRL_ADDRESS_BYTES)}`;

export const QRL_EXAMPLE_ADDRESS_3 =
  `${QRL_ADDRESS_PREFIX}${"20".repeat(QRL_ADDRESS_BYTES)}`;
